server:
  hooks:
    allow_all: true
  listeners:
    healthcheck:
      - id: hc
        port: 8081
    stats:
      - id: stats1
        port: 8080
    tcp:
      - id: tcp1
        port: 1883
    websocket:
      - id: ws1
        port: 1884
  logging:
    level: INFO
    output: JSON
  options:
    capabilities:
      maximum_message_expiry_interval: 100
      compatibilities:
        obscure_not_authorized: true
    
