server:
  hooks:
    allow_all: true
  listeners:
    healthcheck:
      port: 8081
    stats:
      port: 8080
    tcp:
      port: 1883
    websocket:
      port: 1884
  # logging:
  #   level: DEBUG
  options:
    capabilities:
      maximum_message_expiry_interval: 100
      compatibilities:
        obscure_not_authorized: true
    
